# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Code_Audit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Code_Audit(object):
    def setupUi(self, Code_Audit):
        Code_Audit.setObjectName("Code_Audit")
        Code_Audit.resize(397, 297)
        self.textEdit_2 = QtWidgets.QTextEdit(Code_Audit)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 20, 601, 231))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Code_Audit)
        self.pushButton.setGeometry(QtCore.QRect(520, 0, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Code_Audit)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 521, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Code_Audit)
        QtCore.QMetaObject.connectSlotsByName(Code_Audit)

    def retranslateUi(self, Code_Audit):
        _translate = QtCore.QCoreApplication.translate
        Code_Audit.setWindowTitle(_translate("Code_Audit", "Form"))
        self.textEdit_2.setHtml(_translate("Code_Audit", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">&lt;?php<br />    $con=mysqli_connect(&quot;localhost&quot;,&quot;root&quot;,&quot;XFAICL1314&quot;,&quot;dvwa&quot;);<br />    if(mysqli_connect_error())<br />    {<br />        echo &quot;</span><span style=\" font-family:\'宋体\',\'monospace\'; font-size:12pt; color:#000000;\">连接失败</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">:&quot; .mysqli_connect_error();<br />    }<br />    $id=$_GET[\'id\'];<br />    $result=mysqli_query($con,&quot;select * from users where `user_id`=&quot;.$id);<br />    $row=mysqli_fetch_array($result);<br />    echo $row[\'user\'] . &quot;:&quot; . $row[\'password\'];<br />    echo &quot;&lt;br&gt;&quot;;</span></p></body></html>"))
        self.pushButton.setText(_translate("Code_Audit", "Start"))
        self.lineEdit.setText(_translate("Code_Audit", "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"))
