# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Get_CPE.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GetCPE(object):
    def setupUi(self, GetCPE):
        GetCPE.setObjectName("GetCPE")
        GetCPE.resize(400, 300)
        self.label = QtWidgets.QLabel(GetCPE)
        self.label.setGeometry(QtCore.QRect(20, 10, 321, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(GetCPE)
        self.pushButton.setGeometry(QtCore.QRect(270, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(GetCPE)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 251, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(GetCPE)
        QtCore.QMetaObject.connectSlotsByName(GetCPE)

    def retranslateUi(self, GetCPE):
        _translate = QtCore.QCoreApplication.translate
        GetCPE.setWindowTitle(_translate("GetCPE", "Form"))
        self.label.setText(_translate("GetCPE", "测试用例:47.75.212.155  非常非常慢"))
        self.pushButton.setText(_translate("GetCPE", "Start"))
        self.lineEdit.setText(_translate("GetCPE", "IP"))
