# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Converter(object):
    def setupUi(self, Converter):
        Converter.setObjectName("Converter")
        Converter.resize(631, 394)
        self.textEdit_2 = QtWidgets.QTextEdit(Converter)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 30, 601, 231))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Converter)
        self.pushButton.setGeometry(QtCore.QRect(520, 10, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Converter)
        self.comboBox.setGeometry(QtCore.QRect(330, 10, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Converter)
        QtCore.QMetaObject.connectSlotsByName(Converter)

    def retranslateUi(self, Converter):
        _translate = QtCore.QCoreApplication.translate
        Converter.setWindowTitle(_translate("Converter", "Form"))
        self.textEdit_2.setHtml(_translate("Converter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" background-color:#ffffff;\">编解码</span></p></body></html>"))
        self.pushButton.setText(_translate("Converter", "Start"))
        self.comboBox.setItemText(0, _translate("Converter", "b64encode"))
        self.comboBox.setItemText(1, _translate("Converter", "b64decode"))
        self.comboBox.setItemText(2, _translate("Converter", "urlencode"))
        self.comboBox.setItemText(3, _translate("Converter", "urldecode"))
