# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Icmp_Scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Icmp_Scan(object):
    def setupUi(self, Icmp_Scan):
        Icmp_Scan.setObjectName("Icmp_Scan")
        Icmp_Scan.resize(396, 290)
        self.pushButton = QtWidgets.QPushButton(Icmp_Scan)
        self.pushButton.setGeometry(QtCore.QRect(200, 39, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Icmp_Scan)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Icmp_Scan)
        self.label.setGeometry(QtCore.QRect(20, 20, 321, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Icmp_Scan)
        QtCore.QMetaObject.connectSlotsByName(Icmp_Scan)

    def retranslateUi(self, Icmp_Scan):
        _translate = QtCore.QCoreApplication.translate
        Icmp_Scan.setWindowTitle(_translate("Icmp_Scan", "Form"))
        self.pushButton.setText(_translate("Icmp_Scan", "Start"))
        self.lineEdit.setText(_translate("Icmp_Scan", "URL"))
        self.label.setText(_translate("Icmp_Scan", "IcmpScan   测试用例:127.0.0.1"))
