# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rst_Scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rst_Scan(object):
    def setupUi(self, Rst_Scan):
        Rst_Scan.setObjectName("Rst_Scan")
        Rst_Scan.resize(396, 290)
        self.pushButton = QtWidgets.QPushButton(Rst_Scan)
        self.pushButton.setGeometry(QtCore.QRect(200, 39, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Rst_Scan)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Rst_Scan)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Rst_Scan)
        QtCore.QMetaObject.connectSlotsByName(Rst_Scan)

    def retranslateUi(self, Rst_Scan):
        _translate = QtCore.QCoreApplication.translate
        Rst_Scan.setWindowTitle(_translate("Rst_Scan", "Form"))
        self.pushButton.setText(_translate("Rst_Scan", "Start"))
        self.lineEdit.setText(_translate("Rst_Scan", "URL"))
        self.label.setText(_translate("Rst_Scan", "RstScan   测试用例:127.0.0.1"))
