# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search_CVE_Through_CPE.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Search_CVE_Through_CPE(object):
    def setupUi(self, Search_CVE_Through_CPE):
        Search_CVE_Through_CPE.setObjectName("Search_CVE_Through_CPE")
        Search_CVE_Through_CPE.resize(400, 300)
        self.label = QtWidgets.QLabel(Search_CVE_Through_CPE)
        self.label.setGeometry(QtCore.QRect(40, 10, 361, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Search_CVE_Through_CPE)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 251, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Search_CVE_Through_CPE)
        self.pushButton.setGeometry(QtCore.QRect(290, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Search_CVE_Through_CPE)
        QtCore.QMetaObject.connectSlotsByName(Search_CVE_Through_CPE)

    def retranslateUi(self, Search_CVE_Through_CPE):
        _translate = QtCore.QCoreApplication.translate
        Search_CVE_Through_CPE.setWindowTitle(_translate("Search_CVE_Through_CPE", "Form"))
        self.label.setText(_translate("Search_CVE_Through_CPE", "测试用例:cpe:2.3:a:apache:http_server:2.4.47  非常非常慢"))
        self.lineEdit.setText(_translate("Search_CVE_Through_CPE", "CPE"))
        self.pushButton.setText(_translate("Search_CVE_Through_CPE", "Start"))
