# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Syn_Scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Syn_Scan(object):
    def setupUi(self, Syn_Scan):
        Syn_Scan.setObjectName("Syn_Scan")
        Syn_Scan.resize(396, 290)
        self.pushButton = QtWidgets.QPushButton(Syn_Scan)
        self.pushButton.setGeometry(QtCore.QRect(200, 39, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Syn_Scan)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Syn_Scan)
        self.label.setGeometry(QtCore.QRect(20, 20, 331, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Syn_Scan)
        QtCore.QMetaObject.connectSlotsByName(Syn_Scan)

    def retranslateUi(self, Syn_Scan):
        _translate = QtCore.QCoreApplication.translate
        Syn_Scan.setWindowTitle(_translate("Syn_Scan", "Form"))
        self.pushButton.setText(_translate("Syn_Scan", "Start"))
        self.lineEdit.setText(_translate("Syn_Scan", "URL"))
        self.label.setText(_translate("Syn_Scan", "SynScan   测试用例:127.0.0.1"))
