# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WhereIP.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WhereIP(object):
    def setupUi(self, WhereIP):
        WhereIP.setObjectName("WhereIP")
        WhereIP.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(WhereIP)
        self.lineEdit.setGeometry(QtCore.QRect(40, 50, 251, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(WhereIP)
        self.label.setGeometry(QtCore.QRect(40, 30, 231, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(WhereIP)
        self.pushButton.setGeometry(QtCore.QRect(290, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(WhereIP)
        QtCore.QMetaObject.connectSlotsByName(WhereIP)

    def retranslateUi(self, WhereIP):
        _translate = QtCore.QCoreApplication.translate
        WhereIP.setWindowTitle(_translate("WhereIP", "Form"))
        self.lineEdit.setText(_translate("WhereIP", "IP"))
        self.label.setText(_translate("WhereIP", "测试用例:110.242.68.3"))
        self.pushButton.setText(_translate("WhereIP", "Start"))
